[profile.default]
auto_detect_solc     = true
evm_version          = "cancun"
optimizer            = true
optimizer-runs       = 9999999
src                  = "contracts"
out                  = "out"
cache_path           = "cache_forge"
libs                 = ["lib", "dependencies"]

[profile.default.zksync]
src              = "contracts"
out              = "zkout"
libs             = ["lib", "dependencies"]
compile          = true
startup          = true
optimizer        = true
optimizer_mode   = "3"

[dependencies]
"@forge-std" = "1.9.6"
"@forge-zksync-std" = { version = "0.0.1", git = "git@github.com:Moonsong-Labs/forge-zksync-std.git", rev = "c2634a68762ee1e675d4a5c96af850a7ffa28641" }
"@openzeppelin-contracts" = { version = "5.2.0", git = "git@github.com:OpenZeppelin/openzeppelin-contracts.git", rev = "acd4ff74de833399287ed6b31b4debf6b2b35527" }

[soldeer]
remappings_generate   = true
remappings_regenerate = false
remappings_version    = true
remappings_prefix     = "@"
remappings_location   = "txt"
recursive_deps        = false
