name: Foundry CI
on: [workflow_call]
jobs:
  build:
    name: Build contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dutterbutter/foundry-zksync-toolchain@v1
      - run: forge build --zksync --zk-enable-eravm-extensions
